# The name of this GH action
name: Deploy

# Defines when this action should be run
on:
  # Run on any push to main
  push:
    branches:
      - main
  # Run when a repository dispatch event is received
  repository_dispatch:
    types: [openapi-update]

jobs:
  # Deploys the english version
  deploy-en:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      LOCALES: "en"
      EN_OAS3_REPO: "https://github.com/box/box-openapi.git#en"
      EN_POSTMAN_COLLECTION_ID: "8119550-b5ea2aeb-c82a-425d-baff-ed5dfd1d7659"
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Deploy the collection
      run: |
        yarn install
        yarn release en

    - name: Send Slack notification
      uses: Ilshidur/action-slack@2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions
        SLACK_AVATAR: "https://avatars3.githubusercontent.com/u/8659759?s=200&v=4"
      with:
        args: "Deployed English Postman collection :rocket:"

  # Deploys the japanese version
  deploy-jp:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      LOCALES: "jp"
      JP_OAS3_REPO: "https://github.com/box/box-openapi.git#jp"
      JP_POSTMAN_COLLECTION_ID: "8119550-73df4d75-420a-455b-97c2-d3d33103c1a4"
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Deploy the collection
      run: |
        yarn install
        yarn release jp

    - name: Send Slack notification
      uses: Ilshidur/action-slack@2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions
        SLACK_AVATAR: "https://avatars3.githubusercontent.com/u/8659759?s=200&v=4"
      with:
        args: "Deployed Japanese Postman collection :rocket:"